version: "3.8"
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - tor
      - elasticsearch
    volumes:
      - .:/app
    command: python main.py

  tor:
    image: dperson/torproxy
    command: ""
    ports:
      - "9050:9050"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"