services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: python3 main.py
    depends_on:
      - tor
      - elasticsearch

  tor:
    image: dperson/torproxy
    ports:
      - "9050:9050"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"